name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  golang-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
          check-latest: true

      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          go mod tidy

      - name: Test
        env:
          BEARER: ${{ secrets.BEARER }}
          SP_PROJECT_LINK: ${{ secrets.SP_PROJECT_LINK }}
        run: |
          go test ./...
